### ISSUE TITLE
網站使用流程建議

### ISSUE THREAD

**Issue by LuisHsu** [jingfei/burns#1]
1.建議一進入網站的時候改成先顯示"開始計算"，在真正需要緊急計算的時候比較迅速
2.建議在計算頁面，燒燙傷面積/部位的切換部份，改成先顯示輸入部位，理由同上

**Comment by jingfei** [comment]
謝謝您的建議
第二點會列入考量

但第一點 我認為這花不了幾秒鐘的時間 如果不想得知計算方法的話可以直接按下一步
反過來講 再輸入數據之前 知道是使用什麼計算方法是重要的 因此這點我仍然堅持
